baseURL = 'https://zecsec.com/'
languageCode = 'en-us'
title = 'ZecSec: Zcash Ecosystem Security'
theme = 'maverick'
buildDrafts = true

[permalinks]
  pages = "/:slug"

[params]
  logo = '/static/favicon-32.png'
  description = "Zcash Ecosystem Security Support"


[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = -200
  [[menu.main]]
    identifier = "overview"
    name = "Overview"
    url = "/overview/"
    weight = "-160"
  [[menu.main]]
    identifier = "roadmap"
    name = "Roadmap"
    url = "/posts/zecsec-roadmap-for-2023/"
    weight = "-150"
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = "-110"

[markup]
  [markup.tableOfContents]
    endLevel = 2
    ordered = true
    startLevel = 2
